### ISSUE TITLE
Macで共有ライブラリは作れますか?

### ISSUE THREAD

**Issue by s172262** [umezawatakeshi/utvideo#1]
はじめまして。ffmpegをインストールしようとしたところ、 `--enable-libutvideo` というフラグがあったのでこちらにたどり着きました。
こちらのソースを利用させていただいて、Homebrewでlibutvideo.dylibを作ろうとしているのですが
(https://github.com/Homebrew/homebrew-core/pull/729)
、アセンブリコードの部分の取り扱いが分からないため、スタティクしか作れていません。
そもそもはQuickTimeのplug-in向けなので、共有ライブラリ向けに書かれていない可能性もあると思うのですが、当方はスクリプト専門なので、何がどうならbundleではなく共有ライブラリに出来るのかすらわかっていません。すいません。
ffmpegの人達がやっていると思われる libutvideoをbuildするプロジェクトのMakefile(https://github.com/qyot27/libutvideo/blob/buildsystem/GNUmakefile)
では、共有ライブラリを作るときにはアセンブリコードのファイルを除外するようにしているようなのですが、ということはやはり、アセンブリコードの部分は共有ライブラリ向けに書かれていないということなのでしょうか?

作者からすると目的外の話ですいませんが、ご回答いただければ幸いです。

**Comment by umezawatakeshi** [comment]
私は元々 Mac は守備範囲外で、他の QuickTime コーデックコンポーネントのプロジェクトを参考にして作ったため、ちょっと外れたことは残念ながらサッパリ分かりません。

アセンブリコードを除外するようになっているのは、Linux/Mac の 64bit では動かないものが出来上がるからだと思われます。動かないものが出来上がることは認識していますが、Ut Video Codec Suite というプロダクトとしては「それで問題ない」での放置しています。ただし、近い将来に動くように修正する可能性は高いです。

あと、FFmpeg の `--enable-libutvideo` は近いうちに廃止される雰囲気があります。廃止される理由の一つが上に書いてある「Linux/Mac の 64bit では動かないものが出来上がる」なんですけど。
参考: https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2016-February/189014.html

**Comment by s172262** [comment]
ご回答有り難うございました。
梅澤さんが配布されているMac用バイナリが32bit版だけなのはそういうことだったのですか。
アセンブリは一旦諦めます。

あと、梅澤さんはffmpegのソースをご覧になったかどうかわかりませんが、
さっきC++版で16.1.0をビルドして、リンクしようとしたらエラーが出たため、ffmpeg側のソースを見たのですが、**UNFCC**という、かつてutvideoに有った機能を利用していて、それがエラーの原因でした。
ffmpegが現在のバージョンに対応するには大幅な改変が必要だと思われますので、
撤退も有り得そうですね。

**Comment by s172262** [comment]
ffmpegのソースを見てきたのですが、ffmpegは**UNFCC**という型を利用してました。
で、そのUNFCCの宣言が utvideo 15.0.0 から、`utvideo.h`から`Format.h`に移動されたことを
ffmpeg側が認識していないようなので、さっきバグレポートを挙げてきました。
しかし、彼らが`Format.h`の必要性に気付いても、UNFCCは現在は `windef.h`内の変数型で宣言されており、unix環境でUNFCCを利用するのは困難でしょう。

ということで、QuickTime用は16.1.0のバイナリ版を、ffmpeg用には14.2.1を利用させていただくことにします。
