### ISSUE TITLE
cannot manually register VFW on Win8.1 x64

### ISSUE THREAD

**Issue by FredThompsonII** [umezawatakeshi/utvideo#11]
ref: https://forum.doom9.org/showthread.php?p=1797641

I'm trying to register manually for quick silent install/uninstall.

Registry entries are the same for my method and your installer.

Ut is not visible as VFW with my method.
Your install .iss refers to utv_mft.dll which I do not find.

How to manually register Ut .dll files as VFW on Windows x64?

**Comment by umezawatakeshi** [comment]
- Registry entries written in .iss and/or .reg are what I all know.
- Entries about utv_mft.dll in .iss https://github.com/umezawatakeshi/utvideo/blob/f755d1a67b7a1e25406856c6eaa3f9a6ae664f1d/setup_win/setup_win.iss#L89-L90 **uninstall** MFT codecs which used to be contained in UtVideo. Recent versions of UtVideo don't contain MFT codecs.
- You can install UtVideo silently with: `utvideo-17.4.0-win.exe /verysilent` (Of course, privilege elevation dialog may still be displayed)
