### ISSUE TITLE
Add P210 input/output to UQY2 / UQY2 に P210 での入出力を追加する

### ISSUE THREAD

**Issue by umezawatakeshi** [umezawatakeshi/utvideo#16]
Add P210 input/output to UQY2. VirtualDub FilterMod supports P210 input/output.

UQY2 に P210 での入出力を追加する。 VirtualDub FilterMod はコーデックに対して P210 で入出力することができる。

**Comment by shekh** [comment]
Note that P210 output is not implemented yet in VirtualDub FilterMod.
With MagicYUV it works through FOURCC('Y', '3', 10, 10) instead.
There is zero overhead with ('Y', '3', 10, 10), it is simple planar layout (direct match of AV_PIX_FMT_YUV422P10)

**Comment by umezawatakeshi** [comment]
Oops, VDFM supports P210 input from / output to codec, does not support P210 output to AVI file.

I know that Y3[10][10] is a simple planar format but I don't know any software that supports Y3[10][10] input from / output to VFW codec and AVI file. Do you know such software?

**Comment by shekh** [comment]
I am VDFM developer, it currently can:
input P210, Y3[10][10], Y3[10][16] from codec or file
output Y3[10][10], Y3[10][16] to codec
output Y3[10][16] to file
(cannot output Y3[10][10] to file because it requires to put option somewhere)

Output P210 to codec: it passes format negotiation but does not send picture.

Don't know other programs. ffmpeg can write all this to files.

**Comment by umezawatakeshi** [comment]
...oops, sorry...

Support by VDFM is enough. 

> it currently can:
(snip)

It's nice. It would be better if output Y3[10][10] to file is supported.

> Output P210 to codec: it passes format negotiation but does not send picture.
oh...

**Comment by shekh** [comment]
> would be better if output Y3[10][10] to file is supported
What is possible use for such file? Why do you want it?
However it is not a big deal, I can put it in "other formats" list in the "pixel format" dialog.

Output P210 to codec: do you want it? I suspended implementation because there was nothing to gain

**Comment by umezawatakeshi** [comment]
Just because my benchmark tool currently only accepts AVI file, not raw binary (i.e. without any metadata). Not so severe problem. 

P210: If VDFM does not support it, I don't need it now. I just wanted to support some more efficient YUV422 10bit format than v210.

**Comment by shekh** [comment]
With current version P210 can be selected (pixel format->other...)

Y3[10][10] is still not in the menu, but you can write Y3[10][16] (Pixel format->4:2:2 planar 16-bit) and then change FOURCC in DIB header. The only difference is range of values.

**Comment by umezawatakeshi** [comment]
Thank you for implementation. I will try it.

**Comment by umezawatakeshi** [comment]
Released in version 21.1.0 / バージョン 21.1.0 でリリースした。
