### ISSUE TITLE
error: unknown type name 'CodecInfo'

### ISSUE THREAD

**Issue by s172262** [umezawatakeshi/utvideo#2]
たびたびすいません。
MacでXcodeでビルドしようとすると、以下の様なエラーが出ます。
ImageCodec.hの読み込み漏れだと思うのですが。

>In file included from utv_qt/QTCodec.cpp:6:
utv_qt/QTCodec.h:21:60: error: unknown type name 'CodecInfo'; did you mean
      'FolderInfo'?
pascal ComponentResult QTCodecGetCodecInfo(CQTCodec *glob, CodecInfo *info);
                                                           ^~~~~~~~~
                                                           FolderInfo
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Finder.h:252:41: note: 
      'FolderInfo' declared here
typedef struct FolderInfo               FolderInfo;
                                        ^
utv_qt/QTCodec.cpp:15:2: warning: 'GetComponentInfo' is deprecated: first
      deprecated in OS X 10.8 [-Wdeprecated-declarations]
        GetComponentInfo((Component)self, &cd, 0, 0, 0);
        ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Components.h:503:1: note: 
      'GetComponentInfo' has been explicitly marked deprecated here
GetComponentInfo(
^
utv_qt/QTCodec.cpp:17:2: warning: 'SetComponentInstanceStorage' is deprecated:
      first deprecated in OS X 10.8 [-Wdeprecated-declarations]
        SetComponentInstanceStorage(self, (Handle)glob);
        ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Components.h:878:1: note: 
      'SetComponentInstanceStorage' has been explicitly marked deprecated here
SetComponentInstanceStorage(
^
utv_qt/QTCodec.cpp:23:2: warning: 'OpenADefaultComponent' is deprecated: first
      deprecated in OS X 10.8 [-Wdeprecated-declarations]
        OpenADefaultComponent(cd.componentType, kBaseCodecType, &glob->d...
        ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Components.h:1022:1: note: 
      'OpenADefaultComponent' has been explicitly marked deprecated here
OpenADefaultComponent(
^
utv_qt/QTCodec.cpp:24:2: error: use of undeclared identifier
      'ComponentSetTarget'
        ComponentSetTarget(glob->delegateComponent, self);
        ^
utv_qt/QTCodec.cpp:32:3: warning: 'CloseComponent' is deprecated: first
      deprecated in OS X 10.8 [-Wdeprecated-declarations]
                CloseComponent(glob->delegateComponent);
                ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Components.h:593:1: note: 
      'CloseComponent' has been explicitly marked deprecated here
CloseComponent(ComponentInstance aComponentInstance)          __OSX_AVAI...
^
utv_qt/QTCodec.cpp:50:60: error: unknown type name 'CodecInfo'; did you mean
      'FolderInfo'?
pascal ComponentResult QTCodecGetCodecInfo(CQTCodec *glob, CodecInfo *info)
                                                           ^~~~~~~~~
                                                           FolderInfo
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Finder.h:252:41: note: 
      'FolderInfo' declared here
typedef struct FolderInfo               FolderInfo;
                                        ^
utv_qt/QTCodec.cpp:53:2: error: unknown type name 'CodecInfo'; did you mean
      'FolderInfo'?
        CodecInfo **tempCodecInfo;
        ^~~~~~~~~
        FolderInfo
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Finder.h:252:41: note: 
      'FolderInfo' declared here
typedef struct FolderInfo               FolderInfo;
                                        ^
utv_qt/QTCodec.cpp:54:25: error: no member named 'typeName' in 'FolderInfo'
        char name[sizeof(info->typeName)];
                         ~~~~  ^
utv_qt/QTCodec.cpp:56:52: error: use of undeclared identifier
      'codecInfoResourceType'
        err = GetComponentResource((Component)glob->self, codecInfoResou...
                                                          ^
utv_qt/QTCodec.cpp:61:2: warning: 'DisposeHandle' is deprecated: first
      deprecated in OS X 10.8 [-Wdeprecated-declarations]
        DisposeHandle((Handle)tempCodecInfo);
        ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/MacMemory.h:1278:1: note: 
      'DisposeHandle' has been explicitly marked deprecated here
DisposeHandle(Handle h)                                       __OSX_AVAI...
^
utv_qt/QTCodec.cpp:67:9: error: no member named 'typeName' in 'FolderInfo'
                info->typeName[0] = (unsigned char)strlen(name);
                ~~~~  ^
utv_qt/QTCodec.cpp:69:15: error: no member named 'typeName' in 'FolderInfo'
                dst = info->typeName + 1;
                      ~~~~  ^
5 warnings and 8 errors generated.
make: *** [utv_qt/QTCodec.o] Error 1

**Comment by s172262** [comment]
すいません。自己解決というか、解決していないのですが、
当方 OSX 10.11なのですが、ImageCodec.h 内のコメント書き(line 1207)にて、
CodecInfo は 10.9 から廃止されたと書いてあるように読めるのですが。

**Comment by umezawatakeshi** [comment]
はい、廃止されています。なので、古い SDK を使う必要があります。（10.5 の SDK を使っている）

**Comment by s172262** [comment]
ご回答有り難うございました。
Xcodeが「最新のライブラリーに置き換えますか?」と言ってくるのは罠だったのですね。
納得しましたのでCloseします。
