### ISSUE TITLE
Mac install?

### ISSUE THREAD

**Issue by taji** [umezawatakeshi/utvideo#25]
I've used UTVideo on Windows and love it.  But does UTVideo support macos?  If so any instructions on how to install?

**Comment by umezawatakeshi** [comment]
No. UtVideo doesn't support Mac now.

macOS dropped support of QuickTime (more precisely, QuickTime components) at macOS 10.15 Catalina. As far as I know, current macOS doesn't have well-documented multimedia plugin API for third party video/audio codecs.

**Comment by taji** [comment]
Wow, that clarifies ALOT.  I had no idea.  Thanks for the info.
