### ISSUE TITLE
Add UQY0 with YUV420P16 input/output (was: YUV420P16)

### ISSUE THREAD

**Issue by nobananasforyou** [umezawatakeshi/utvideo#28]
Hello,

Could you please implement support for YUV420P16. I want to use utvideo and virtualdub2 for my lossless encodes.

Thank you!

**Comment by umezawatakeshi** [comment]
Let me clarify the request:

- You want new codec variant "UtVideo Pro YUV420 10bit (UQY0)" and its support for YUV420P16 input/output.

Is it right?

**Comment by nobananasforyou** [comment]
Yes, please. It is supported by vdub2, avs+, and vapoursynth.

Refer: https://sourceforge.net/p/vdfiltermod/wiki/format_changes/

**Comment by umezawatakeshi** [comment]
OK.

**Comment by umezawatakeshi** [comment]
Released in version 21.0.0

**Comment by nobananasforyou** [comment]
Thank you!

**Comment by umezawatakeshi** [comment]
Could you submit a new issue?

**Comment by nobananasforyou** [comment]
I created a separate issue for that. I can't get utvideo to output p016, whereas it works with ffv1. I could be doing something wrong.

https://www.dropbox.com/s/rbsepxlyd1rnbf7/a.PNG?dl=0
https://www.dropbox.com/s/yl7uuzlbxbx315q/b.PNG?dl=0

test samples:
https://www.dropbox.com/s/tfg7915i8omgwea/ut_16.mkv?dl=0
https://www.dropbox.com/s/sgg6cpsnxtb7wsv/ffv1_16.mkv?dl=0

mpc error log:
LAV Splitter Source (internal)::Video
UQY0 Decoder DMO::out0

Media Type 0:
--------------------------
Video: Y3 720x480 23.976fps

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: Unknown GUID Name {100B3359-0000-0010-8000-00AA00389B71}
formattype: FORMAT_VideoInfo {05589F80-C356-11CE-BF01-00AA0055595A}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 0
cbFormat: 88

VIDEOINFOHEADER:
rcSource: (0,0)-(720,480)
rcTarget: (0,0)-(720,480)
dwBitRate: 0
dwBitErrorRate: 0
AvgTimePerFrame: 417083

BITMAPINFOHEADER:
biSize: 40
biWidth: 720
biHeight: 480
biPlanes: 1
biBitCount: 24
biCompression: Y3
biSizeImage: 1036800
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 d0 02 00 00 e0 01 00 00 ........Ð...à...
0010: 00 00 00 00 00 00 00 00 d0 02 00 00 e0 01 00 00 ........Ð...à...
0020: 00 00 00 00 00 00 00 00 3b 5d 06 00 00 00 00 00 ........;]......
0030: 28 00 00 00 d0 02 00 00 e0 01 00 00 01 00 18 00 (...Ð...à.......
0040: 59 33 0b 10 00 d2 0f 00 00 00 00 00 00 00 00 00 Y3...Ò..........
0050: 00 00 00 00 00 00 00 00                         ........

**Comment by umezawatakeshi** [comment]
Again, create one issue for one topic.

---

No wonder. You said that you want YUV420P16 I/O. You didn't mention P016 at all.
