### ISSUE TITLE
Feature request: Y16 Input/Output

### ISSUE THREAD

**Issue by nobananasforyou** [umezawatakeshi/utvideo#29]
Sorry about not being more clearer.

**Comment by umezawatakeshi** [comment]
You first clarify your request.

**Comment by nobananasforyou** [comment]
Y 4:0:0 16bit.

**Comment by umezawatakeshi** [comment]
You do not state **what** should support Y16 I/O.

**Comment by nobananasforyou** [comment]
I want utvideo to support Y 4:0:0 16it input and output for vdub2.
