### ISSUE TITLE
There is no direct NV12 input, so the cpu had to transform it into YV12. IT is an unnecessary painful work for a lot of CPU

### ISSUE THREAD

**Issue by Cuberlain** [umezawatakeshi/utvideo#32]
Hi!

There is no direct NV12 input for UT Video, so the cpu had to transform it into YV12. NV12 is more common in cameras and camcorders than YV12 format, especially all famous camcorder and camera manufacturers (Sony, Panasonic, JVC, Canon)  use only the NV12 color format, when they send the signal trough HDMI output in yuv 4:2:0 colorspace.
It is a lot of CPU work to transform it to YV12, especially if you want to record video with a laptop. That unnecessary transform operation increases the CPU usage with 100-200 percent on many laptops , which has not dedicated strong videocards.

Can you make a YUV 4:2:0  NV12 version?

Thank you for your reply!

**Comment by umezawatakeshi** [comment]
I opened a same issue (#17) long ago, but I have leave it undone for a long time.

Now I received your request, so it's time to implement it!

**Comment by Cuberlain** [comment]
> so it's time to implement it!

Thank you Umezawatakeshi!
NV12 is similar to YV12 format in many respects. Maybe it can use the same compression technology.
When will you implement it in the next release?

Thank you for your reply!

Best wishes!

**Comment by umezawatakeshi** [comment]
It will be released in the next version, but I make no guarantee when the next version is released.

**Comment by Cuberlain** [comment]
Can you make a YV12 version too?

I often capture videos from 4k camcorders with Elgato Cam Link 4K in VirtualDub2, which have nv12 source video.
However there are HSW colorspace problems, which can be solved by the so-called "swap U and V" transformation :(((

**Comment by umezawatakeshi** [comment]
I don't implement any workarounds for other buggy components (except OS itself). It is just a waste of my life.

**Comment by Cuberlain** [comment]
Hello Umezawatakeshi!

Addig an important new type of colorspace mode is a great update itself for a codecs.
I can't wait :) When will you release the new codecs? 
If you have a dev. vesion , I can test it with pleasure!

Best wishes!

**Comment by umezawatakeshi** [comment]
In version 22.1.0, which is released just now, ULY0 and ULH0 support NV12 input/output.

**Comment by Cuberlain** [comment]
Thank you Umezawatakeshi!
It  is good to see that Ut video is better than MagicYUV, and Ut video also support more color formats.
