### ISSUE TITLE
What are the FFMPEG settings codes of Ut video in OBS?

### ISSUE THREAD

**Issue by Cuberlain** [umezawatakeshi/utvideo#35]
Hello Umezawatakeshi !

I would like to know, what are the FFMPEG settings codes of Ut video in OBS?

Thank you for your reply and help!

Picture of the issue:

https://i.ibb.co/jwn8wZq/k-p.png

Best regards!
Bye!

**Comment by umezawatakeshi** [comment]
OBS doesn't use my implementation (The implementation in FFmpeg is not written by me). I don't know how to configure it.

**Comment by jpovixwm** [comment]
Hi. You can get a list of the available options by invoking ffmpeg as follows: `ffmpeg --help encoder=utvideo`.
The output will look something like this:
```
Encoder utvideo [Ut Video]:
    General capabilities: threads
    Threading capabilities: frame
    Supported pixel formats: gbrp gbrap yuv422p yuv420p yuv444p
utvideo AVOptions:
  -pred              <int>        E..V...... Prediction method (from 0 to 3) (default left)
     none            0            E..V......
     left            1            E..V......
     gradient        2            E..V......
     median          3            E..V......
```
