### ISSUE TITLE
How can I defend my selected UTvideo format from the arbitrary decision of a capture software?

### ISSUE THREAD

**Issue by Cuberlain** [umezawatakeshi/utvideo#37]
Hello Umezawatakeshi!

In many capture/recorder softwares you can choose from many types of Utvideo codecs. In some softwares however neglect my choice. For example: I chose ULH0 in Daum's Potplayer, when I want to record from an NV12 camcorder device, but somehow the result is always captured in RGB color. So the capture softwares can overwrite my original choice (ULH0) and put the video arbitrarily into RGB format? How is it possible?
Is this a bug in their potplayer?
I can't write to Potplayer, because I couldn't even register to their forum. (maybe their website has technical problems)
https://potplayer.daum.net/forum/ucp.php?mode=login

Thank you for your reply!
Best regards!

Bye!

Picture from my options in potplayer:
First: 
https://i.ibb.co/FB8XbWH/k-p.png

Second:

https://i.ibb.co/vctTN85/k-p.png

Picture from the result:

https://i.ibb.co/6XgxnkL/k-p.png

**Comment by umezawatakeshi** [comment]
Since potplayer is the one who selects the codec, I can't answer your question. Ask the potplayer. I've never heard of it.

Just because there is a problem in the potplayer forum doesn't mean you may ask me.
