### ISSUE TITLE
YUV option to switch between limited TV (16-235) and full PC (0-255) colorspace

### ISSUE THREAD

**Issue by Walcund** [umezawatakeshi/utvideo#38]
Hi Umezawatakeshi!

Can you implement a YUV option to switch between limited TV (16-235) and full PC (0-255) colorspace?

It would be very important!
Thank you very much!

**Comment by umezawatakeshi** [comment]
You have to explain why/how it is important for you or for other users.

**Comment by Walcund** [comment]
Hi!

Lossless codecs (like the Ut video) are mostly used **for video capture** from analog or digital sources. This would be just an option to enforce the legal TV (16-235) spectrum, which is World standard for all major  (Sony Panasonic JVC Canon etc... ) camcorder manufacturers and TV  producers. This function would be further ensure the right TV color spectrum if the user activate it optionally (if he want).
When YUV sources are played back on RGB (monitor like) computer color standard, the full spectrum (0-255) can cause brutal black in the dark parts of a picture and blown out in the lighter areas of the picture.

See the picture:
http://s018.radikal.ru/i526/1402/0a/2568d4334e88.jpg

**Comment by umezawatakeshi** [comment]
I'm afraid that I don't understand why YUV fullrange is needed from that explanation. hmm...

**Comment by Walcund** [comment]
> 
> 
> I'm afraid that I don't understand why YUV fullrange is needed from that explanation. hmm...

You have right. 

It is enough to give a one 1 click option. An option for limited range (TV 16-235), and if it is not selected than Ut video will interpret automatically as full range. And it is enough for the YUV 4:2:0 encoders.

**Comment by umezawatakeshi** [comment]
Wait a minute. Do you mean that you think the current UtVideo handles YUV as fullrange?

**Comment by Walcund** [comment]
Hi Umezawatakeshi!
I can not prove it, but I recorded video from an SONY FDR-AX53 camcorder, first with the internal 4K AVC encoder of the camcorder, than with UT video from a Cam-Link-4K HDMI-to-USB3 converter adapter to a LAPTOP SSD with the help of Ut-video and Virtualdub2.

Of course it is a very long chain....until the the signals of the image sensor transforms into an ut video file of the SSD of the laptop.
In every step of the above mentioned chain can have a bad intrpretation of the TV range and Full range. That's why I said I am can not be 100% sure in this. :(

**Comment by umezawatakeshi** [comment]
Anyway, as written in readme, UtVideo handles YUV in a limited range.
Make sure you know what's going on in your environment before you come back.
