### ISSUE TITLE
Huffman+Median+Interlaced  result in garbage output

### ISSUE THREAD

**Issue by tvasenin** [umezawatakeshi/utvideo#45]
I use Behold TV to capture video into UTVideo ASF.

Huffman+(Median or Gradient)+Interlaced results in garbage output:

![image](https://user-images.githubusercontent.com/376100/226620952-271e7767-8d2c-4bae-ac96-1c23d29b5788.png)

![image](https://user-images.githubusercontent.com/376100/226621346-c0ba7392-fd37-49cd-a59f-dded29c4d8ad.png)

If required, I can provide the sample video file.

**Comment by umezawatakeshi** [comment]
seems same reason as https://github.com/umezawatakeshi/utvideo/issues/44
