### ISSUE TITLE
UTVideo and ffmpeg

### ISSUE THREAD

**Issue by dgalland** [umezawatakeshi/utvideo#47]
Hello and thank you for this excellent codec ! 
I have more a question than an issue.
When I use UTVideo from ffmpeg something like this:
ffmpeg -i in.avi  -c:v utvideo  -pix_fmt yuv422p  out.avi
The chosen codec is always ULY2 in the BT601 colorspace. Is it possible to select the BT709 codec ?
Does this really have a consequence?
Best regards.

**Comment by richardpl** [comment]
You can use ULH2 if you set the colorspace parameter.

**Comment by dgalland** [comment]
Thank you for this quick response and happy new year!
It's actually quite simple and I should have thought of it :
ffmpeg -i in.avi -c:v utvideo -pix_fmt yuv422p -colorspace  bt709 out.avi
and it works
Do we know the version of UTvideo that is embedded in ffmpeg ?
Best regards

**Comment by richardpl** [comment]
ffmpeg does not use this repo utvideo implementation at all, that is why encoding is 8bit only.
